### ISSUE TITLE
Can't type Chinese or show Chinese in KeenWrite

### ISSUE THREAD

**Issue by JackQAQ-byte** [DaveJarvis/keenwrite#103]
**Description**
Can't type or show Chinese
![Screenshot_20201101_092825](https://user-images.githubusercontent.com/66677431/97793271-d998c400-1c24-11eb-9a8e-0d0356367212.png)

**Replicate**
Copy Chinese, Paste Chinese

**Expected**
Show Chinese

**Actual**
Didn't show

**Screenshots**
given

**Environment**
 - Operating System: openSUSE, KDE
 - Application: 1.9.1

**Details**
Thannks! :)

**Comment by DaveJarvis** [comment]
Duplicate of #94
