### ISSUE TITLE
The About menu item does not list the version number of keenwrite

### ISSUE THREAD

**Issue by johnblommers** [DaveJarvis/keenwrite#110]
**Description**
The About window does not cite the revision number of keenwrite

**Replicate**
Exact and complete steps to reproduce the problem 100% of the time:

1. Click Help
1. Click About

**Expected**

The version number should be listed. 

**Actual**

The version number is not listed.

**Environment**
 - Operating System:  Linux/Pop!_OS 20.10

**Comment by DaveJarvis** [comment]
Workaround: Run the application from the command-line to see the version number.

**Comment by DaveJarvis** [comment]
Fixed on mainline.
