### ISSUE TITLE
FilePickerFactory doesn't close JWFileChoosers

### ISSUE THREAD

**Issue by io7m** [DaveJarvis/keenwrite#125]
Hello! Just spotted this issue:

https://github.com/DaveJarvis/keenwrite/blob/b76f233b038e057b593efedbd0e53f32ef1f9208/src/main/java/com/keenwrite/ui/explorer/FilePickerFactory.java#L69

Note that the `JWFileChoosers` class creates an executor for performing background I/O:

https://github.com/io7m/jwheatsheaf/blob/develop/com.io7m.jwheatsheaf.ui/src/main/java/com/io7m/jwheatsheaf/ui/JWFileChoosers.java#L82

The executor is shut down in the corresponding `close` method:

https://github.com/io7m/jwheatsheaf/blob/develop/com.io7m.jwheatsheaf.ui/src/main/java/com/io7m/jwheatsheaf/ui/JWFileChoosers.java#L196

Unfortunately, your use of the class will result in effectively leaking a thread each time you open a new file picker (if I'm understanding your code correctly). The right thing to do is more likely to move the `mChooserType` field into the `FilePickerFactory` class, assuming that `FilePickerFactory` instances are cleaned up at some point.

**Comment by DaveJarvis** [comment]
Fixed on mainline.
