### ISSUE TITLE
Cannot Find List of Supported Languages

### ISSUE THREAD

**Issue by alliter8** [DaveJarvis/keenwrite#126]
This is a question only. I could not find a list of languages that are supported in this this editor; please considering adding it to your readme.

Additionally, I personally would like to know if reStructuredText or Asciidoc are supported?

**Comment by DaveJarvis** [comment]
> This is a question only. I could not find a list of languages that are supported in this this editor

Great question. There's a https://github.com/DaveJarvis/keenwrite/discussions page for any future questions.

Most, if not all, left-to-right languages should be supported by configuring fonts and locale. I haven't tested with right-to-left or top-to-bottom writing. There were some recent changes to the RichTextFX text editor that may be necessary to support them. I'm not sure, though, sorry.

> Additionally, I personally would like to know if reStructuredText or Asciidoc are supported?

The architecture design doesn't prohibit them:

https://raw.githubusercontent.com/DaveJarvis/keenwrite/master/docs/images/architecture/architecture.png

However, they aren't implemented, yet.
