### ISSUE TITLE
Convert straight quotes to curly quotes

### ISSUE THREAD

**Issue by DaveJarvis** [DaveJarvis/keenwrite#127]
# Background

The ConTeXt typesetting engine (a.k.a. [LMTX](https://wiki.contextgarden.net/LMTX)) does not convert straight quotes (i.e., `"` and `'`) into curly quotes (i.e., `“`, `”`, `‘`, and `’`). In English prose, quite often there is sufficient contextual information to categorize straight quotes within a paragraph as their curly counterparts. Regular expressions, such as those defined by the [SmartQuotes](https://github.com/DaveJarvis/keenwrite/blob/master/src/main/java/com/keenwrite/quotes/SmartQuotes.java) class are less accurate than a formal grammar.

# Technical

There are a few conceptual parts to creating the quotation parser grammar. The first parts, which are currently coded in [**English.g4**](https://github.com/DaveJarvis/keenwrite/blob/127_convert_straight_quotes/quotes/English.g4) _almost_ work:

* **Double quotes.** Detect opening and closing quotes in a few different contexts: speech quotations, air quotes, multi-paragraph quotations, and a mix of single- and multi-paragraph quotations. See [english.txt](https://github.com/DaveJarvis/keenwrite/blob/127_convert_straight_quotes/quotes/english.txt) for examples.
* **Single quotes.** Detect and distinguish apostrophes and single opening/closing quotes. Opening/closing single quotes have the same logic as opening/closing double quotes; contractions make extensive use of apostrophes, which can be distinguished from opening/closing single quotes in that: apostrophes always modify a word but closing quotes are _usually_ preceded by punctuation (′air quotes’ notwithstanding).

The following parts haven't been started:

* **Prime quotes.** Detect single- and double-straight apostrophes as prime and double-prime values. These are usually bound to numerals (e.g., angles 4° 5' 30'' and heights 5'11").
* **LaTeX quotes.** Detect double-backticks and double-straight apostrophes, which represent opening/closing double quotes, respectively. Like straight double-quotes, the pair doesn't need to be balanced because quotations may cross paragraph boundaries.
* **Curly quotes.** Detect curly single/double quotes, primes, and double-primes within the prose. These would be similar to an identity transform or no-op, if you will, and may be needed to properly handle multi-line paragraphs when users mix straight and curly quotes in both balanced and unbalanced scenarios.
* **Nested quotes.** Alternating double/single quotations and nested brackets should be possible. See [nested.txt](https://github.com/DaveJarvis/keenwrite/blob/127_convert_straight_quotes/quotes/nested.txt) for an example. Nested "air quotes" would be great, too, but aren't all that important---I suspect that they may lead to ambiguous situations.
* **Escaped quotes.** Sometimes straight quotes are escaped (e.g., `\"` and `\'`). The backslash should be ignored to treat the quotation mark as it would normally be interpreted. (Pandoc treats an escaped straight quote verbatim, which may become a future feature.)

Separate from **English.g4** would be **Markup.g4**, which builds upon **English.g4** to parse prose written in an XHTML document. Essentially:

* **Markup quotes.** Augment the grammar with XHTML detection. For example, instead of using new lines to differentiate paragraphs, the grammar will use `<p>...</p>`. This will affect how apostrophes are detected. Inline HTML tags such as `<strong>` and `<em>` redefine what is meant by a "word". The text `<p><em>Captain <strong>Janeway</strong>'s Adventures</em></p>` would emit with an `apostrophe` token, effectively ignoring the HTML elements. Inline- and block-level elements that must be emitted verbatim include: `<tex>`, `<pre>`, `<tt>`, and `<code>`.

The `<tex>` element will be entirely parsed and typeset using the typesetting engine software. Authors must type curly quotes, if needed, directly into the TeX code.

## Testing

The `grun.sh` shell script in the `quotes` directory can be used to test the grammar against a text file:

``` bash
git clone https://github.com/DaveJarvis/keenwrite.git
cd keenwrite/quotes
./grun.sh > english.log
./grun.sh simple.txt > simple.log
```

The script parses `english.txt` by default; the text files include:

* **english.txt** -- basic sentence and paragraph tests
* **math.txt** -- TeX code
* **multiquote.txt** -- quotations that span multiple paragraphs
* **nested.txt** -- example with nested quotes
* **simple.txt** -- single paragraph with multiple sentences
* **xhtml.txt** -- XHTML file having block and inline elements

All these would result in a valid parse tree. 

## Output

The output is a Java class that can parse a text file into an in-memory parse tree. The parse tree must be able to reliably reproduce the original input document or throw an exception that indicates the location in the document where parsing failed (i.e., typical ANTLR behaviour). The following table lists the tokens that the parse tree must contain, where the **Entity** column provides an example of how the token may be used for conversion:

| Token  | Description | Entity |
| --- | --- | --- |
| `openingDQuote` | opening double quote | `&ldquo;` |
| `openingSQuote` | opening single quote | `&lsquo;` |
| `closingDQuote` | closing double quote | `&rdquo;` |
| `closingSQuote` | closing single quote | `&rsquo;` |
| `apostrophe` | curled apostrophe | `&apos;` |

All other non-empty parse tree items should be readily exported verbatim, such as the tokens listed in the following table:

| Token  | Description | Examples |
| --- | --- | --- |
| `openingTag` | any opening XHTML element |`<p>`, `<tex>`, `<b>`, `<div class="note">` |
| `closingTag` | any closing XHTML element |`</p>`, `</tex>`, `</b>`, `</div>` |
| `selfTag` | any self-closing XHTML element |`<br/>`, `<hr/>` |
| `letters` | sequence of letters forming a word | `flabbergasted` |

The token `letters` can be taken to mean letter, number, or Unicode symbol that would normally be found within a word.

# Acceptance

Acceptance criteria includes grammar definition files that can be used by ANTLR to produce Java parsers. The files include:

* **English.g4** -- Handles test `.txt` files (except `xhtml.txt` and `math.txt`).
* **Markup.g4** -- Handles test `.txt` files (including `xhtml.txt` and `math.txt`).
* **English.lex** -- Optionally, common lexer definitions shared by English and Markup grammars.

Parse trees from either **.g4** grammar file would allow converting straight quotes to curly quotes.

## grun

Running `./grun.sh filename.txt` will not result in an error when provided any:

* text file without XHTML elements and using **English.g4** (such as `simple.txt`); or
* text file and using **Markup.g4** (such as `xhtml.txt` or `math.txt`).

## Goal

In addition to the `.txt` files listed in the testing section, in theory it should be possible to use the file grammars to convert each straight quote in [smartypants.txt](https://github.com/DaveJarvis/keenwrite/blob/127_convert_straight_quotes/src/test/resources/com/keenwrite/quotes/smartypants.txt) to its curly quote equivalent. The file contains input and expected output values. Having **.g4** grammar files is sufficient to replace the [SmartQuotes](https://github.com/DaveJarvis/keenwrite/blob/master/src/main/java/com/keenwrite/quotes/SmartQuotes.java) class with one that uses the parse tree to perform the conversion.

**Comment by DaveJarvis** [comment]
The following passage from _The Mill on the Floss_ has its quotation marks already converted:

> “Not much o’ fellow-creaturs, I think, Miss; all I know—my old master, as war a knowin’ man, used to say, says he, ‘If e’er I sow my wheat wi’out brinin’, I’m a Dutchman,’ says he; an’ that war as much as to say as a Dutchman war a fool, or next door. Nay, nay, I aren’t goin’ to bother mysen about Dutchmen. There’s fools enoo, an’ rogues enoo, wi’out lookin’ i’ books for ’em.”

It's a pretty good example of single-quotes nested inside of double-quotes with a mix of ye olde contractions.

**Comment by DaveJarvis** [comment]
@bkiers -- any update?

**Comment by bkiers** [comment]
@DaveJarvis sorry, ran into a tricky ambiguity which I couldn't resolve. Will post my findings here outside my working hours.

**Comment by bkiers** [comment]
@DaveJarvis I've created a draft PR so that you can easily see what I've tried: https://github.com/DaveJarvis/keenwrite/pull/130

**Comment by DaveJarvis** [comment]
Fixed on main.
