### ISSUE TITLE
PDF export fails without meaningful diagnostics

### ISSUE THREAD

**Issue by johnblommers** [DaveJarvis/keenwrite#128]
Keenwrite 2.0.0 has a great new typesetting feature. But when it fails the Menu &rarr; View &rarr; Issues is not particularly helpful. Is there not more diagnostic information that might be logged there?

A simple Markdown test file typeset just fine here. A much more complex document not so much. For example what is to be done about this:

![Screenshot from 2021-05-10 21-11-44](https://user-images.githubusercontent.com/8484427/117757136-590adf80-b1d4-11eb-87e0-9dac12ba6183.png)

My guess is that it's related to images linking, but at what line number in the Markdown document is the offense committed? Without that information the user is hard pressed to move ahead with typesetting. And when we launch Keenwrite on the commandline there's nothing there besides one message:

> "*OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.*"

**Comment by DaveJarvis** [comment]
Fixed on main branch.
