### ISSUE TITLE
Create variables using GUI button

### ISSUE THREAD

**Issue by marcusyoung** [DaveJarvis/keenwrite#132]
I'm just exploring keenwrite. I understand how variables are defined in a yaml file. I'm not clear how the Create button in the GUI is meant to be used. How should information be entered to create a variable. I tried, name:marcus and that created this in the yaml file:

`
'name: marcus': {}`
`
Also the delete and rename buttons don't seem to do anything.

Thanks.

**Comment by DaveJarvis** [comment]
See the following discussion:

https://github.com/DaveJarvis/keenwrite/discussions/134#discussioncomment-970697

If this doesn't answer your question, see:

https://github.com/DaveJarvis/keenwrite/blob/master/docs/variables.md

If you're still stuck, please reply in the discussions area, thank you.
