### ISSUE TITLE
It unpacks to which directories? How I uninstall?

### ISSUE THREAD

**Issue by patarapolw** [DaveJarvis/keenwrite#135]
> Note that the first time the application runs, it will unpack itself into a local directory. Subsequent starts will be faster.

**Comment by DaveJarvis** [comment]
There is no uninstall because there is no installation. The application extracts itself on Windows into the following directory:

C:\Users\%USERNAME%\AppData\Local\warp\packages\keenwrite.exe

Delete the `C:\Users\%USERNAME%\AppData\Local\warp\` directory to remove the software from your system.

**Comment by patarapolw** [comment]
I don't use Windows.

I guess it's `~/.local/share/warp` in Linux.
