### ISSUE TITLE
Simple GraphViz diagram fails to render

### ISSUE THREAD

**Issue by DaveJarvis** [DaveJarvis/keenwrite#138]
As per a [discussion](https://github.com/DaveJarvis/keenwrite/discussions/137) item:

1. Start KeenWrite.
1. Create a new file.
1. Paste the following contents:

        ``` diagram-graphviz
        digraph G {
          Hello->World
        }
        ```

**Expected:** The diagram renders.

**Actual:**

The status bar shows an I/O exception (HTTP 400) along with the following stack trace in the log:

````
18 Sep. 2021 10:26:52		com.keenwrite.io.HttpFacade$Response.<init>(HttpFacade.java:94)
com.keenwrite.io.HttpFacade.httpGet(HttpFacade.java:40)
com.keenwrite.io.HttpFacade.httpGet(HttpFacade.java:51)
com.keenwrite.preview.SvgReplacedElementFactory.createReplacedElement(SvgReplacedElementFactory.java:60)
com.keenwrite.preview.ChainedReplacedElementFactory.lambda$createReplacedElement$0(ChainedReplacedElementFactory.java:81)
java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
com.keenwrite.preview.ChainedReplacedElementFactory.createReplacedElement(ChainedReplacedElementFactory.java:79)
````

**Comment by DaveJarvis** [comment]
There seems to be a difference in the encoding schemes applied with JavaScript and Java, at least for short texts. KeenWrite generates the following base64- and URL-encoded text for the string `"digraph G {Hello->World; World->Hello;}"`:

    eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSbFWAFO6dmBB61oAE9kN

Whereas Kroki's demo page, using JavaScript, generates:

    eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSbFWAFO6dmBB61oAE9kNww==

The only difference is `ww==`.

**Comment by DaveJarvis** [comment]
The issue may be caused by a difference in Pako's deflate algorithm and Java's deflate algorithm. This results in some (short) diagrams not rendering in KeenWrite. Consider the following GraphViz code:

    digraph G {Hello->World; World->Hello;} 

Using Kroki's online tool (Pako-based deflate), the following Base64-encoded URL is generated:

    https://kroki.io/graphviz/svg/eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSbFWAFO6dmBB61oAE9kNww== 

Using KeenWrite (Java-based deflate), the following Base64-encoded URL is generated, which Kroki cannot render (missing the trailing ww==):

    https://kroki.io/graphviz/svg/eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSbFWAFO6dmBB61oAE9kN 

The deflated binary data differs by two bytes.

Java deflate:

    [120, 218, 75, 201, 76, 47, 74, 44, 200, 80, 112, 87, 168, 246, 72, 205, 201, 201, 215, 181, 11, 207, 47, 202, 73, 177, 86, 0, 83, 186, 118, 96, 65, 235, 90, 0, 19, 217, 13] 

Pako deflate:

    [120, 156, 75, 201, 76, 47, 74, 44, 200, 80, 112, 87, 168, 246, 72, 205, 201, 201, 215, 181, 11, 207, 47, 202, 73, 177, 86, 0, 83, 186, 118, 96, 65, 235, 90, 0, 19, 217, 13, 195] 

Should both deflate algorithms, given the same input bytes, produce the same output bytes when using the same compression level? If so, which deflate algorithm is problematic?

The following block diagram was generated using KeenWrite and can be decoded by Kroki, which implies KeenWrite's usage of Java's Deflater class is correct:

https://kroki.io/blockdiag/svg/eNpdzDEKQjEQhOHeU4zpPYFoYesRxGJ9bwghMSsbUYJ4d10UCZbDfPynolOek0Q8FsDeNCestoisNLmy-Qg7R3Blcm5hPcr0ITdaB6X15fv-_YdJixo2CNHI2lmK3sPRA__RwV5SzV80ZAegJjXSyfMFptc71w==

**Comment by Mogztter** [comment]
I'm not a deflate expert but I believe my code is wrong: https://docs.kroki.io/kroki/setup/encode-diagram/#java
I just tried another implementation and Kroki can decode it:

```java
private static byte[] compress(byte[] source) throws IOException {
  Deflater deflater = new Deflater();
  deflater.setInput(source);
  ByteArrayOutputStream outputStream = new ByteArrayOutputStream(source.length);
  deflater.finish();
  byte[] buffer = new byte[1024];
  while (!deflater.finished()) {
    int count = deflater.deflate(buffer); // returns the generated code... index
    outputStream.write(buffer, 0, count);
  }
  outputStream.close();
  byte[] output = outputStream.toByteArray();
  return output;
}
```

For reference, here's the code I'm using to decode (inflate): https://github.com/yuzutech/kroki/blob/main/server/src/main/java/io/kroki/server/decode/Zlib.java

Here's another implementation that seems to work:

```java
private static byte[] compress(byte[] source) throws IOException {
  Deflater deflater = new Deflater();
  deflater.setInput(source);
  deflater.finish();

  byte[] bytesCompressed = new byte[Short.MAX_VALUE];
  int numberOfBytesAfterCompression = deflater.deflate(bytesCompressed);
  byte[] returnValues = new byte[numberOfBytesAfterCompression];
  System.arraycopy(bytesCompressed, 0, returnValues, 0, numberOfBytesAfterCompression);
  return returnValues;
}
```

**Comment by DaveJarvis** [comment]
Fixed, thank you.

**Comment by Mogztter** [comment]
Thanks for confirming.
I've created a pull request upstream to update the code and documentation: https://github.com/yuzutech/kroki/pull/912
