### ISSUE TITLE
Theme - Monokai

### ISSUE THREAD

**Issue by mery6299** [DaveJarvis/keenwrite#149]
**New UI theme**
I noticed that the aplication does not have a monokai theme, so I made one.
That's my first try on themes, so it might not be perfect. Though, it looks decent to me.

The .css is not supported as a part of issue, so it's uploaded as a txt.
[Monokai.txt](https://github.com/DaveJarvis/keenwrite/files/7822379/Monokai.txt)

**Comment by DaveJarvis** [comment]
Thank you very much for the contribution! Let me know if you'd like the attribution changed. Will be in the next release. Here are my tweaks:

* Change the caret colour to white (black and black is hard to see)
* Change the text selection to a darker, derived blue.
* Change the search selection to a darker, derived yellow.
* Change the spelling error colour to orange.

https://github.com/DaveJarvis/keenwrite/blob/master/src/main/resources/com/keenwrite/skins/monokai.css

**Comment by mery6299** [comment]
The attribution seems good to me.
Thanks for the tweaks, simple changes, but it looks a bit better now.
