### ISSUE TITLE
Can't find keenwrite.jar

### ISSUE THREAD

**Issue by nhpackard** [DaveJarvis/keenwrite#151]
**Description**
Can't find keenwrite.jar

**Replicate**
```
$ ./keenwrite.sh 
Error: Unable to access jarfile keenwrite.jar
```
**Expected**
as described in README.md:
"The application is started."

**Actual**
Application doesn't start

**Environment**
 - mac OS 10.14.6
```
 $ java -version
openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment (build 17+35-LTS)
OpenJDK 64-Bit Server VM (build 17+35-LTS, mixed mode, sharing)
```

**Details**
Maybe download link simply needs to be fixed?
```
$ wget https://gitreleases.dev/gh/DaveJarvis/keenwrite/latest/keenwrite.jar
--2022-04-25 17:45:05--  https://gitreleases.dev/gh/DaveJarvis/keenwrite/latest/keenwrite.jar
Resolving gitreleases.dev (gitreleases.dev)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘gitreleases.dev’
```

Looks like great functionality.  I would like to try it!

**Comment by DaveJarvis** [comment]
Thank you for the bug report. I've updated the links in the README document.

- https://github.com/DaveJarvis/keenwrite/releases/latest/download/keenwrite.jar
- https://github.com/DaveJarvis/keenwrite/releases/latest/download/keenwrite.exe
- https://github.com/DaveJarvis/keenwrite/releases/latest/download/keenwrite.bin

Please re-open the issue if the download doesn't work.

Also, be sure to use the FULL edition of Java 17, which bundles JavaFX.
