### ISSUE TITLE
use jpackage to provide installers for different targets

### ISSUE THREAD

**Issue by nimo23** [DaveJarvis/keenwrite#156]
Hello,

would be nice to package this application by [jpackage](https://docs.oracle.com/en/java/javase/18/jpackage/packaging-overview.html#GUID-DAE6A497-6E6F-4895-90CA-3C71AF052271) (or [launch4j](http://launch4j.sourceforge.net/)) to provide different packages (keenwrite.dmg, keenwrite.exe, etc.).

**Comment by DaveJarvis** [comment]
The application is packaged using [warp-packer](https://github.com/dgiagio/warp) into `.bin`, `.exe`, and `.jar` files. This is accomplished with the following constraints:

* Binary package for all target platforms can be built on Linux, Windows, or MacOS (i.e., must support cross-platform builds)
* Binary package must be a self-contained executable file (no installer)
* Binary package must have ability to run as CLI or GUI application
* Building all binaries must be possible from the command-line

When I looked into jpackage, it could not be used to create a `.exe` when building on Linux. That is, to create a binary you had to build that binary on the target platform. That may have changed.

When I looked into launch4j, it required an installer. I checked again, prompted by this ticket, and didn't see a way to make an application that supports both a GUI and CLI operations.

KeenWrite can be built on any platform (that supports `bash`) and target any platform. For example, on Linux, I can do the following:

    ./installer.sh --os windows

That will produce a `.exe` file. I can also do:

    ./release.sh

That will produce the `.bin`, `.exe`, and `.jar` files.

If you'd like to provide the exact, highly detailed, step-by-step instructions to cross-compile KeenWrite on Linux to produce self-contained, installer-free executable files for Windows, Linux, and MacOS, I'll replace warp-packer.

A PR that replaces the functionality of `installer.sh` and `release.sh` would also be welcome. For example, if you wanted to update the Gradle build scripts such that the following work on any platform:

``` bash
gradle clean build jar
gradle clean build windows
gradle clean build macos
gradle clean build linux
```

That would be a huge improvement.

On the other hand, if all you're looking for is a `.dmg` file, a PR that modifies the scripts to invoke warp-packer for MacOS would be most welcome. Take a look at lines 200 to 210 of `installer.sh` for details.

Thanks for the note!

**Comment by DaveJarvis** [comment]
Another possibility is [packr](https://github.com/libgdx/packr), which appears to support all the required functionality.

**Comment by DaveJarvis** [comment]
Note: I am strongly opposed to "installers" per se. Programs should "just work" without requiring any configuration steps before they can be used. Download, double-click, and use. No installation needed.

**Comment by nimo23** [comment]
> I am strongly opposed to "installers" per se. Programs should "just work"

Yes, I think so too. However, such a `jar` does not necessarily run (as it is) on every platform. With jpackager (or packr) it would be possible to include the runtime (for jre _and_ javafx) right away, so that the user does not have to install (or change) the java runtime environment himself. In addition, most of them do not necessarily have the JavaFX runtime installed. A dmg would also increase the acceptance for Mac OS users with following benefits. Maybe, I have time in future to dig into it and provide a PR..

**Comment by DaveJarvis** [comment]
I may be missing something here, @nimo23.

The [download](https://github.com/DaveJarvis/keenwrite#download) section offers:

* https://github.com/DaveJarvis/keenwrite/releases/latest/download/keenwrite.exe
* https://github.com/DaveJarvis/keenwrite/releases/latest/download/keenwrite.bin

Both of those come bundled with a JRE and JavaFX. For other platforms:

https://github.com/DaveJarvis/keenwrite#other

Step 1 is to download the "full version" with a link to BellSoft's JRE, which comes bundled with JavaFX.

> Maybe, I have time in future to dig into it and provide a PR.

Having a clean way to build self-contained executable files that run on any platform would be greatly appreciated. I don't think jpackager can cross-compile, though, so packr might be the only viable option.

**Comment by nimo23** [comment]
>Both of those come bundled with a JRE and JavaFX. For other platforms:

I have already another OpenJDK distribution installed. Therefore, I installed JavaFX manually and have the javafx-path included within `keenwrite.sh by adding `--module-path`:

```
java \
  --module-path $JAVA_FX \
  ...
  -jar keenwrite.jar $@
```

`$JAVA_FX `points correctly to:

```
echo $JAVA_FX
/Library/Java/Extensions/javafx-sdk-18.0.2/lib/javafx-sdk-12.0.1/lib
```

However, I get this error:

`Error: --module-path requires module path specification`

**Comment by nimo23** [comment]
My fault, I forgot to `add-modules`:

```
java \
  --module-path $JAVA_FX_HOME \
  --add-modules javafx.swing,javafx.graphics,javafx.fxml,javafx.media,javafx.controls \
..
```

The app opens and it works as usual. A bit annoying that the terminal is also open and active as long as the app is running..

**Comment by DaveJarvis** [comment]
I've been making a little headway in this area. There are a few items that need to change before native binaries can be made for all platforms:

* Swap Renjin with FastR
* Build using GraalVM
* Integrate with GitHub build process to cross-compile

I strongly dislike that third part, but there really might not be any other option at this point. This will also solve the "delete existing directory" issue with upgrading on Windows.
