### ISSUE TITLE
Add VERSION INFO to Windows executable

### ISSUE THREAD

**Issue by novomesk** [DaveJarvis/keenwrite#158]
Hello Dave,

I am getting orange detection alert from my anti-virus software:
![keenwrite_detection_warning](https://user-images.githubusercontent.com/52529860/194352727-377fdc44-7a5a-4b57-b384-6d7c33af13dc.png)

I see that keenwrite.exe is not signed nor it doesn't have a VERSION INFO (those common attributes like CompanyName, FileDescription, FileVersion, LegalCopyright, OriginalFilename, ProductName, ProductVersion).

I know that digital certificate is expensive (I also don't have it on my programs) but at least I think that adding the VERSION INFO would help some of the security programs to be less suspicious.

I would also suggest to add a program icon to the keenwrite.exe file.

**Comment by DaveJarvis** [comment]
Fixed in 3.0.0.
