### ISSUE TITLE
How to draw sequence diagram?

### ISSUE THREAD

**Issue by leyley** [DaveJarvis/KeenWrite#164]
How to draw sequence diagram?
I can't find any document about it, could you please give me some examples?

**Comment by DaveJarvis** [comment]
See:

* https://github.com/DaveJarvis/KeenWrite/discussions/137
* https://www.youtube.com/watch?v=vIp8spwykZY

Try:

``` diagram-seqdiag
seqdiag {
  browser  -> webserver [label = "GET /seqdiag/svg/base64"];
  webserver  -> processor [label = "Convert text to image"];
  webserver <-- processor;
  browser <-- webserver;
}
````

![seqdiag](https://user-images.githubusercontent.com/2131950/228057547-55ab2d13-7240-48b8-969d-c077fd5bc235.png)
