### ISSUE TITLE
Clarify JavaFX requirement in readme

### ISSUE THREAD

**Issue by kwin** [DaveJarvis/KeenWrite#167]
Currently the readme only states for the JAR:

> Download the Full version of the Java Runtime Environment, [JRE 20](https://bell-sw.com/pages/downloads).

As that distribution is quite unusual, there should be some hints on how to install OpenFX on top of an existing JDK distribution (e.g. Eclipse Temurin). There are some hints in https://openjfx.io/openjfx-docs/#modular
Also there should be a dedicated system prerequisites section which states that both Java 20+ and JavaFX are required.
Also the `.sh` script should be extended to optionally add a custom module path.

**Comment by DaveJarvis** [comment]
Added a note to the section on running the JAR, thank you. If you want to extend the launcher shell script, open a PR.
