### ISSUE TITLE
Use dockable panels for UI

### ISSUE THREAD

**Issue by madeindjs** [DaveJarvis/keenwrite#65]
IMO preview panel is not useful when I write something. It could be great to hide it when I wan't with a shortcurt or a menu item.

**Comment by DaveJarvis** [comment]
Dockable panels, such as those by [DockFX](https://github.com/RobertBColton/DockFX), provide a way to configure the major components of the application, including (from left to right):

* Definition pane
* File editor pane
* HTML preview pane

The goal is to allow the user to customize the application layout to their needs. This would support, for example:

* Hiding the preview pane
* Hiding the definition pane
* Moving the definition pane to the right (or below)

This is required in preparation to add the following new panels:

* File system tree view
* Error message log (e.g., to show a history of errors from R and other aspects of the application)

**Comment by DaveJarvis** [comment]
After an extensive review of over a dozen docking frameworks for JavaFX, only TiwulFX 3.1 came close to meeting all the requirements. Unfortunately, the docking code was tangled with additional components. A trimmed down version of just the docking code has been forked into its own repository:

https://github.com/DaveJarvis/PitchDockFX

A message has been sent to the original author asking for a standalone library for the docking framework. Should that happen and be comparable in size and functionality to PitchDockFX, then migrating away from PitchDockFX may be feasible (to reduce maintenance burden).

**Comment by DaveJarvis** [comment]
Ability to hide the preview is on mainline.
