### ISSUE TITLE
File system explorer

### ISSUE THREAD

**Issue by DaveJarvis** [DaveJarvis/keenwrite#68]
Integrate a file system explorer panel so that users can select browse to and select files for editing from within the IDE--without having to use the **File > Open** dialog.

This is predicated on having the dockable panels in place.

Multiple file system explorer panels should be possible.

See: https://github.com/TomasMikula/LiveDirsFX

**Comment by m1k3io** [comment]
This is coming along great! I'm looking forward to this feature as it would be handy for exploring files in the same location as the markdown files.

**Comment by DaveJarvis** [comment]
Simple prototype on mainline. Next release will allow many dockable file system explorers.

**Comment by DaveJarvis** [comment]
@m1k3io, this feature is now available in the latest release. Additional feedback is most welcome.
