### ISSUE TITLE
Option-Key on Mac Doesn't Work

### ISSUE THREAD

**Issue by ingomohr** [DaveJarvis/keenwrite#82]
On Mac you use the Option-Key for guards or curly brackets.
Using the option key with Scrivenvar has no effect - it doesn't add a char for apparently any key.

**Comment by DaveJarvis** [comment]
@ingomohr, are you able to investigate why this happens and issue a PR?

**Comment by ingomohr** [comment]
@DaveJarvis , yes, I could trow a glance at the code within the next week, I think.

**Comment by ingomohr** [comment]
Hi @DaveJarvis, do you have some introduction on how to setup the project for running / debugging in an IDE?

I was looking for it in the wiki of this repo and the readme/build files in the project, but I didn't find something in that direction.

It took me now 1h of trying to set the project up for debugging, but it looks like this:

<img width="1292" alt="Screenshot 2020-09-22 at 22 49 45" src="https://user-images.githubusercontent.com/2838592/93936374-66975600-fd26-11ea-8beb-0f7c43857d67.png">

* This was in Eclipse 2020-09 w/ latest BuildShip 3.1.4
* I learned from BuildShip bug that I had to use the Gradle import wizard because simply importing the project via eGit doesn't work so I can refresh the project via Gradle -> Refresh Project.
* So I used the Gradle import wizard, and this is the result.

Before that...
* I've tried to set up the project manually and (since I've been using Maven until now) had to learn how to get Gradle to copy all the libs into some libs folder
  * (btw - why are there 2 JARs in the repo and all the other don't?)
* After I manually configured classpath, libs etc, the project built except of one compiler error complaining about not finding some xml.ErrorListener (don't have the code anymore, sorry).

So, for now, I'll leave this with the kind suggestion of providing some welcoming page for potential contributors. It's "Preptember" anyway, so maybe this is a good opportunity to get contributors create some pull requests for you in Hacktober ;)

Hope you're safe and well
Ingo

**Comment by DaveJarvis** [comment]
@ingomohr, find updated build instructions at:

https://github.com/DaveJarvis/keenwrite/blob/master/BUILD.md

Will revise with Eclipse instructions shortly.

**Comment by DaveJarvis** [comment]
I see why it took over an hour to configure. JavaFX support in Eclipse has a lot of finicky bits. I made some headway with the following instructions:

## Eclipse

This section describes how to build and run the application using Eclipse.
The instructions are for the _Eclipse IDE for Java Developers_, other
installs may not work with the steps that follow.

### Import

Complete the following steps to import the application:

1. Start the IDE.
1. Ensure the **Package Explorer** is open.
1. Click **Import projects**.
1. Expand **Gradle**.
1. Select **Existing Gradle Project**.
1. Click **Next**.
1. Click **Next** again.
1. Click **Browse**.
1. Browse to the directory containing `keenwrite`.
1. Click **Open**.
1. Click **Finish**.

The application is imported, but will not build until JavaFX is registered
with Eclipse.

Register JavaFX as follows:

1. Click **Help → Install New Software**.
1. Set **Work with** to: `http://download.eclipse.org/efxclipse/updates-released/1.2.0/site/`
1. Press `Enter` to download the software descriptions.
1. Check **e(fx)clipse - install**.
1. Check **e(fx)clipse - single components**.
1. Click **Next**.
1. Click **Next** again.
1. Accept the license agreement.
1. Click **Finish**.
1. Wait for the **Certificates** dialog to appear.
1. Click **Accept selected**.
1. Click **Restart Now**.

The JavaFX add-on to Eclipse is installed. Continue as follows:

1. Restart Eclipse, if needed.
1. Re-open the project, if needed.
1. Right-click the project.
1. Select **Properties**.
1. Select **Java Build Path**.
1. Click the **Libraries** tab.
1. Select **Classpath**.
1. Click **Add Library**.
1. Select **JavaFX SDK**.
1. Click **Finish**.
1. Click **Apply and Close** to close the properties dialog.

At this point, I received the following error:

> The package javafx.application is accessible from more than one module: <unnamed>, javafx.graphics

This indicates that two modules are in conflict. Most of the solutions suggest using `exclude group` to ensure that only one module is using JavaFX, where the other can be transitive. The `build.gradle` file already does this for the packages that reference JavaFX.

At this point, I'm at a loss.

IntelliJ IDEA reuses the Gradle build process, so it builds and runs without any issues.

**Comment by ingomohr** [comment]
Good morning - and thank you! I'll check tonight whether I can spot the cause for this issue. 😊

**Comment by ingomohr** [comment]
Hey @DaveJarvis . Thank you for assigning me. Sorry, I didn't have the time yesterday. Will attend soon to this issue.

**Comment by ingomohr** [comment]
Hi @DaveJarvis 

I finally came to spend some time on this one - and I now decided to drop it.
Here's why.

- I very likely won't ever use this application for markdown editing
  - simply because I usually work either in Eclipse or VSCode
    - and for both it is rather hard to integrate keenwrite into
    - also, there already is MD support
- I am not familiar w/ JavaFX (jumped from Swing directly to SWT)
  - Handling with JavaFX feels rather complicated.
  - And I don't think I will use JavaFX for one of my projects
  - I tried JavaFX Key(Code)Combination ALT_ANY and Key BRACKET_OPEN and other combination in KeyListeners
    - had no effect at all. The listener was not called.
- I think there's more than the Option-Key problem (at least on macOS)
  - maybe you don't have the effect on Windows or Linux, but on Mac it's something like this (started out of IntelliJ - thanks btw for the how-to in the build.md ❤️)
  - see the Gif
  - I took a new fork of your repo today - commit was [this](https://github.com/DaveJarvis/keenwrite/commit/a84b11f443878e12584ef379a7bf21b7e4eb2a7a).

![editor-typing-problem](https://user-images.githubusercontent.com/2838592/101290341-df745d00-3801-11eb-8ae9-97b3074cd718.gif)

From a glance, I would guess that the code replaces the text on the editor pane while typing. At least I had those kind of effects with SWT before, too, when I replaced something (in the wrong way).

I am sorry for dropping this issue. But I think it's fair to both you and me to admit that I won't invest more time in this problem and instead work on other projects.

You can close this issue if you feel it's the best.

Kind regards
Ingo

**Comment by DaveJarvis** [comment]
Thanks @ingomohr.

I'm hoping that the https://github.com/DaveJarvis/keenwrite/tree/1_refactor_docking branch will resolve this issue. It's an extensive refactor of the code with many simplifications.

Thanks again for looking into this and providing an update.
