### ISSUE TITLE
Complete Damian Conway's rules for English pluralization

### ISSUE THREAD

**Issue by DaveJarvis** [DaveJarvis/keenwrite#95]
The file [pluralize.R](https://github.com/DaveJarvis/keenwrite/blob/master/R/pluralize.R) contains an _incomplete_ implementation of [Damian Conway's "An Algorithmic Approach to English Pluralization"](http://blob.perl.org/tpc/1998/User_Applications/Algorithmic%20Approach%20Plurals/Algorithmic_Plurals.html). Implementations exist that either complete or partially complete the algorithm, such as:

* Oliver Glerke's Evo Inflector, https://github.com/atteo/evo-inflector/
* Shevek's Pluralizer, https://github.com/shevek/linguistics/
* Jazzband's inflect, https://pypi.org/project/inflect/2.0.0/
* Bob Rudis', https://cran.r-project.org/web/packages/pluralize/index.html
* Blake Embrey's, https://github.com/plurals/pluralize

The following rules, and possibly more, are unimplemented in pluralize.R: 3, 6, and 7.

Ideally, we would have:

* All rules are implemented.
* Tests for at least two words from each rule (in a separate test).
* Internationalized

**Comment by rgertenbach** [comment]
Hi, as discussed in the email thread I'll take a stab at this :)

**Comment by rgertenbach** [comment]
Hey Dave, quick followup, I couldn't find a testing framework in renjin,how would this best be implemented, could I just add unit tests using test that or do you have an existing framework for that?

**Comment by DaveJarvis** [comment]
Two approaches. First:

1. Create `https://github.com/DaveJarvis/keenwrite/tree/master/src/test/R`
1. Create a `pluralize-test.R` file.
1. Import from `../../../R/pluralize.R`
1. Create a shell script to run the tests.

See:

* https://towardsdatascience.com/unit-testing-in-r-68ab9cc8d211
* https://testthat.r-lib.org/

Second is to use JUnit with Renjin. For this, take a look at:

* https://github.com/DaveJarvis/keenwrite/blob/master/src/main/java/com/keenwrite/processors/InlineRProcessor.java#L73 - Shows how to instantiate Renjin.
* https://github.com/DaveJarvis/keenwrite/blob/71dd454c5ef7160fc318f2a579ba48139bafcf91/src/main/java/com/keenwrite/processors/InlineRProcessor.java#L111 - Shows loading the bootstrap script.
* https://github.com/DaveJarvis/keenwrite/blob/master/src/test/java/com/keenwrite/tex/TeXRasterization.java#L76 - Shows an existing unit test.

The overall algorithm would be:

1. Create a new class inside https://github.com/DaveJarvis/keenwrite/tree/master/src/test/java/com/keenwrite/tex
1. Load the Renjin scripting engine (as per `InlineRProcessor.java`).
1. Set Renjin's working directory to the `R` directory.
1. Use Renjin instance to execute `source( 'pluralize.R' )`.
1. Create a unit test that verifies the calls to pluralize against a variety of words.

**Comment by rgertenbach** [comment]
Quick update: been struggling with getting Java set up to run as I don't normally use it much. I'll go with the second option you proposed which is also the one I'm more familiar with.  I'll keep the tests simple to keep them portable

**Comment by DaveJarvis** [comment]
>  Quick update: been struggling with getting Java set up to run as I don't normally use it much.

If it makes any difference, IntelliJ should be straightforward, but isn't necessary. A starter unit test on the main branch. See https://github.com/DaveJarvis/keenwrite/blob/master/src/test/java/com/keenwrite/r/PluralizeTest.java for details.

At this point, it can be edited with any editor, then validated by running `gradle test` from within the same directory as `build.gradle`.

**Comment by rgertenbach** [comment]
Sorry for the radio silence, work has been hectic and I had to put this on the backburner for a while.

So far I implemented all rules except 12 and you can pick whether you prefer modern, classical or a mixed pluralization.

I'm almost done, the only things missing are:

- Rule 12 (Compound words) 
- checking if I can port the tests to the Java version (current tests are in testthat with a bash script)

I should have a PR ready soon.

**Comment by DaveJarvis** [comment]
@rgertenbach, let me know if you need a hand with porting to Java or building the application. The main branch has had significant updates and I may have disabled some tests.

**Comment by rgertenbach** [comment]
Been a long time again despite having been so close.
I now have all rules working separately and end to end, I'll pull the latest version of the program and will try to integrate

**Comment by DaveJarvis** [comment]
@rgertenbach -- any update?

**Comment by rgertenbach** [comment]
Hey, really sorry, I have been swamped at work.
TBH I don't know if and when I'll be able to the integration into the actual program, especially as I'm not familiar with the latest changes.

Check out the [code](https://gist.github.com/rgertenbach/bf0d4678f07f041e7875375e7dfeabbc) and the [tests](https://gist.github.com/rgertenbach/ba9a87c3344e6a97ed3d561917b08ce0) (can be run with `R < pluralize-test.R`  
Assumes the files are in src/main/r and src/test/r.

**Comment by DaveJarvis** [comment]
Fixed on main branch, will be available in the next release.

Thank you @rgertenbach !
